import type { NextPage } from "next";
import Head from "next/head";
import HomeComponent from "../components/Home/Home";
import AboutComponent from "../components/About/About";
import ContactComponent from "../components/Contact/Contact";
import ServicesComponent from "../components/Services/Services";

const Home: NextPage = () => {
  return (
    <div id={"container"}>
      <Head>
        <title>Dr Kannan Physiotherapy Clinic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/jpg" href="/favicon.png" />
      </Head>

      <main className={"main"}>
        <div className="App">
          <HomeComponent />
          <AboutComponent></AboutComponent>
          <ServicesComponent></ServicesComponent>
          <ContactComponent></ContactComponent>
        </div>
      </main>
    </div>
  );
};

export default Home;
